//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DLWEBEntities : DbContext
    {
        public DLWEBEntities()
            : base("name=DLWEBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OfficeDLW> OfficesDLW { get; set; }
        public virtual DbSet<Recruitment_DlWeb> Recruitment_DlWeb { get; set; }
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Brochure> Brochures { get; set; }
        public virtual DbSet<SubDepartment> SubDepartments { get; set; }
        public virtual DbSet<WebsitePagesSubDepartment> WebsitePagesSubDepartments { get; set; }
    }
}
