//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_ITInfo
    {
        public long auto_number { get; set; }
        public string Emp_Code { get; set; }
        public string typist_name { get; set; }
        public string typist_email { get; set; }
        public string extension_no { get; set; }
        public string Email { get; set; }
        public string Network_Username { get; set; }
        public string Network_Password { get; set; }
        public string Osprey_Acc_Created { get; set; }
        public string Osprey_Username { get; set; }
        public string Osprey_Password { get; set; }
        public string feeearner_code { get; set; }
        public string bb_mobile_no { get; set; }
        public string bb_simcard_no { get; set; }
        public string bb_imei_no { get; set; }
        public string notes { get; set; }
        public string Computer_Name { get; set; }
        public string Location { get; set; }
        public string Inventory_Signed { get; set; }
        public string Personal_Portal_Created { get; set; }
        public string Staff_Personal_Portal_Username { get; set; }
        public string Staff_Persona_Portal_Password { get; set; }
        public string Butterworths_Email_Updates_Created { get; set; }
        public string DDn { get; set; }
        public string Access_To_HR_Database { get; set; }
        public string Perm_Level { get; set; }
        public string swipcard_number { get; set; }
        public string swipcards_taken { get; set; }
        public string fingerprints_taken { get; set; }
        public Nullable<System.DateTime> Exch_ID_Created_Date { get; set; }
        public Nullable<System.DateTime> Exch_ID_Deleted_Date { get; set; }
        public string Network_Username_Created { get; set; }
        public string OutLook_Acct_Created { get; set; }
        public string OutLook_Username { get; set; }
        public string OutLook_Password { get; set; }
        public string sign_title { get; set; }
        public string sign_jobtitle { get; set; }
        public string sign_title1 { get; set; }
        public string sign_title2 { get; set; }
        public string sign_title3 { get; set; }
        public string sign_dx { get; set; }
        public string sign_fax { get; set; }
        public string sign_office { get; set; }
        public string laptop_given { get; set; }
        public string remote_access_given { get; set; }
        public string dictaphone_given { get; set; }
        public Nullable<System.DateTime> Emp_ITInfo_created_stamp { get; set; }
        public string Emp_ITInfo_created_user { get; set; }
        public string Emp_ITInfo_created_version { get; set; }
        public string Emp_ITInfo_created_user_Program { get; set; }
        public string Emp_ITInfo_created_machine_name { get; set; }
        public string Emp_ITInfo_created_ip { get; set; }
        public Nullable<System.DateTime> Emp_ITInfo_modified_stamp { get; set; }
        public string Emp_ITInfo_modified_user { get; set; }
        public string Emp_ITInfo_modified_version { get; set; }
        public string Emp_ITInfo_modified_user_program { get; set; }
        public string Emp_ITInfo_modified_machine_name { get; set; }
        public string Emp_ITInfo_modified_ip { get; set; }
        public string old_swipcard_number { get; set; }
        public string rdp_mobile_number { get; set; }
        public string INDIGO_Userid { get; set; }
        public Nullable<System.DateTime> IndigoAccount_EndDate { get; set; }
        public string service_tag { get; set; }
        public string emp_email_code { get; set; }
        public string department_it { get; set; }
    }
}
