//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emp_Profile
    {
        public string emp_code { get; set; }
        public string jobtitle { get; set; }
        public Nullable<System.DateTime> datejoined { get; set; }
        public string department { get; set; }
        public string education { get; set; }
        public string prof_memship { get; set; }
        public string email { get; set; }
        public string office { get; set; }
        public string experience { get; set; }
        public string mem_and_int { get; set; }
        public string web_permission { get; set; }
        public string keywords { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string updated_by { get; set; }
        public Nullable<System.DateTime> Emp_Profile_created_stamp { get; set; }
        public string Emp_Profile_created_user { get; set; }
        public string Emp_Profile_created_version { get; set; }
        public string Emp_Profile_created_Program { get; set; }
        public string Emp_Profile_created_machine_name { get; set; }
        public string Emp_Profile_created_ip { get; set; }
        public Nullable<System.DateTime> Emp_Profile_modified_stamp { get; set; }
        public string Emp_Profile_modified_user { get; set; }
        public string Emp_Profile_modified_version { get; set; }
        public string Emp_Profile_modified_program { get; set; }
        public string Emp_Profile_modified_machine_name { get; set; }
        public string Emp_Profile_modified_ip { get; set; }
    }
}
