//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRDDLEntities : DbContext
    {
        public HRDDLEntities()
            : base("name=HRDDLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<Emp_Details> Emp_Details { get; set; }
        public virtual DbSet<Emp_ITInfo> Emp_ITInfo { get; set; }
        public virtual DbSet<Emp_Profile> Emp_Profile { get; set; }
    }
}
