//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IT_DatabaseEntities : DbContext
    {
        public IT_DatabaseEntities()
            : base("name=IT_DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Updates_MainWebsites> Updates_MainWebsites { get; set; }
        public virtual DbSet<User_Profile> User_Profile { get; set; }
        public virtual DbSet<Website_Department_Structure> Website_Department_Structure { get; set; }
        public virtual DbSet<Website_Pages> Website_Pages { get; set; }
        public virtual DbSet<Website_Pages_SubDepartments> Website_Pages_SubDepartments { get; set; }
        public virtual DbSet<website_awards> website_awards { get; set; }
        public virtual DbSet<website_Header_Pictures> website_Header_Pictures { get; set; }
        public virtual DbSet<User_Profile_FinalDraft> User_Profile_FinalDraft { get; set; }
        public virtual DbSet<Website_Custom_SubDepartments> Website_Custom_SubDepartments { get; set; }
        public virtual DbSet<SubDepartmentSwitchboard> SubDepartmentSwitchboards { get; set; }
        public virtual DbSet<PhotoSession_StaffAttendance> PhotoSession_StaffAttendance { get; set; }
        public virtual DbSet<PhotoSession> PhotoSessions { get; set; }
        public virtual DbSet<MobileNoFor_ITIssues> MobileNoFor_ITIssues { get; set; }
        public virtual DbSet<SubDepartmentProfile> SubDepartmentProfiles { get; set; }
        public virtual DbSet<Website_Videos> Website_Videos { get; set; }
        public virtual DbSet<StaffProfilesCreatedLog> StaffProfilesCreatedLogs { get; set; }
        public virtual DbSet<Website_Structure> Website_Structure { get; set; }
        public virtual DbSet<SubDepartmentProfileStructure> SubDepartmentProfileStructures { get; set; }
        public virtual DbSet<LogsOfModification> LogsOfModifications { get; set; }
        public virtual DbSet<Updates_MainWebsite_Departments> Updates_MainWebsite_Departments { get; set; }
        public virtual DbSet<website_Office_Direction> website_Office_Direction { get; set; }
    }
}
