//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileNoFor_ITIssues
    {
        public int Id { get; set; }
        public string Emp_Code { get; set; }
        public Nullable<bool> Notification_Req { get; set; }
        public string System_Username { get; set; }
        public string Mobile_Auth { get; set; }
        public Nullable<System.DateTime> Date_Updated { get; set; }
    }
}
