//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public Office()
        {
            this.Emp_Details = new HashSet<Emp_Details>();
        }
    
        public string office_code { get; set; }
        public string office_desc { get; set; }
        public string office_address { get; set; }
        public string office_addrText { get; set; }
        public string office_type { get; set; }
        public string operation_statusO { get; set; }
        public string office_name { get; set; }
        public string office_geo_location { get; set; }
        public Nullable<System.DateTime> datecreated { get; set; }
        public Nullable<System.DateTime> dateclosed { get; set; }
        public string county { get; set; }
        public Nullable<bool> office_status { get; set; }
        public string office_dx_no { get; set; }
        public string organization_supplier_number { get; set; }
        public Nullable<System.DateTime> created_stamp { get; set; }
        public string created_user { get; set; }
        public string created_version { get; set; }
        public string created_Program { get; set; }
        public string created_machine_name { get; set; }
        public string created_ip { get; set; }
        public Nullable<System.DateTime> modified_stamp { get; set; }
        public string modified_user { get; set; }
        public string modified_version { get; set; }
        public string modified_program { get; set; }
        public string modified_machine_name { get; set; }
        public string modified_ip { get; set; }
        public string postcode { get; set; }
        public Nullable<bool> isswipemachine_present { get; set; }
        public string telephone_office_code { get; set; }
        public string indigo_office_code { get; set; }
        public byte[] fb { get; set; }
        public byte[] twitter { get; set; }
        public byte[] linkedin { get; set; }
        public Nullable<bool> TrainingPlan_office { get; set; }
        public Nullable<bool> Main_Office { get; set; }
    
        public virtual ICollection<Emp_Details> Emp_Details { get; set; }
    }
}
