//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoSession_StaffAttendance
    {
        public int Id { get; set; }
        public int EventId { get; set; }
        public string EmpName { get; set; }
        public Nullable<bool> Attendance { get; set; }
        public string Notes { get; set; }
    }
}
