//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffProfilesCreatedLog
    {
        public int Id { get; set; }
        public string emp_code { get; set; }
        public Nullable<System.DateTime> date_created { get; set; }
    }
}
