//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubDepartmentProfile
    {
        public int Id { get; set; }
        public string emp_code { get; set; }
        public string Profile { get; set; }
        public string SubDepartment { get; set; }
        public string StaffName { get; set; }
        public Nullable<int> SubDepartmentProfileStructureId { get; set; }
        public Nullable<bool> Selected { get; set; }
        public bool Approve { get; set; }
        public string ApprovedProfile { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> WarningColorCode { get; set; }
        public string WarningMessage { get; set; }
        public string ip_address { get; set; }
        public Nullable<bool> FurtherActionRequired { get; set; }
        public string FurtherActionRequiredMessage { get; set; }
        public Nullable<System.DateTime> FurtherActionRequiredDate { get; set; }
    
        public virtual SubDepartmentProfileStructure SubDepartmentProfileStructure { get; set; }
    }
}
