//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubDepartmentProfileStructure
    {
        public SubDepartmentProfileStructure()
        {
            this.SubDepartmentProfiles = new HashSet<SubDepartmentProfile>();
        }
    
        public int Id { get; set; }
        public string Department1 { get; set; }
        public string Department2 { get; set; }
        public string SubDepartment { get; set; }
        public string BuzzWords { get; set; }
        public Nullable<bool> Enabled { get; set; }
    
        public virtual ICollection<SubDepartmentProfile> SubDepartmentProfiles { get; set; }
    }
}
