//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Profile
    {
        public long Id { get; set; }
        public string Emp_code { get; set; }
        public string Emp_Name { get; set; }
        public string Profile { get; set; }
        public string Profile_Status { get; set; }
        public string Education { get; set; }
        public string Education_Status { get; set; }
        public string Career { get; set; }
        public string Career_Status { get; set; }
        public string Client_Comments { get; set; }
        public string Client_Comments_Status { get; set; }
        public string Supreme_Court { get; set; }
        public string Supreme_Court_Status { get; set; }
        public string Court_of_Appeal { get; set; }
        public string Court_of_Appeal_Status { get; set; }
        public string High_Court { get; set; }
        public string High_Court_Status { get; set; }
        public string Criminal_Court { get; set; }
        public string Criminal_Court_Status { get; set; }
        public string Civil_Court { get; set; }
        public string Civil_Court_Status { get; set; }
        public string Other_Supreme_Court { get; set; }
        public string Other_Supreme_Court_Status { get; set; }
        public string Other_Court_of_Appeal { get; set; }
        public string Other_Court_of_Appeal_Status { get; set; }
        public string Other_High_Court { get; set; }
        public string Other_High_Court_Status { get; set; }
        public string Other_Criminal_Court { get; set; }
        public string Other_Criminal_Court_Status { get; set; }
        public string Other_Civil_Court { get; set; }
        public string Other_Civil_Court_Status { get; set; }
        public string Dir_RecAndAwards { get; set; }
        public string Dir_RecAndAwards_Status { get; set; }
        public string MembershipAndAccreditations { get; set; }
        public string MembershipAndAccreditations_Status { get; set; }
        public string Personal_Interests { get; set; }
        public string Personal_Interests_Status { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Quality_Status { get; set; }
        public Nullable<bool> Html_Status { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public Nullable<System.DateTime> Quality_Date { get; set; }
        public Nullable<System.DateTime> Html_Date { get; set; }
        public Nullable<bool> Final_Status { get; set; }
        public Nullable<System.DateTime> Final_Date { get; set; }
        public string Dept { get; set; }
        public string Dept2 { get; set; }
        public string Profile2 { get; set; }
        public string Dept3 { get; set; }
        public string Profile3 { get; set; }
        public string Dept4 { get; set; }
        public string Profile4 { get; set; }
        public string Drafts_status { get; set; }
        public string Page_Title { get; set; }
        public string Page_Description { get; set; }
        public string Page_Keywords { get; set; }
    }
}
