//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website_Pages_SubDepartments
    {
        public string department { get; set; }
        public string Sub_department { get; set; }
        public int sequence1 { get; set; }
        public int Id { get; set; }
        public string link { get; set; }
    }
}
