//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class website_Office_Direction
    {
        public int ID { get; set; }
        public string Direction_From_Site { get; set; }
        public string Category_Of_Site { get; set; }
        public string AddressandDescription_of_Site { get; set; }
        public string Map_Of_Site { get; set; }
        public string DirectionByWalk { get; set; }
        public string DirectionByBus { get; set; }
        public Nullable<int> officeid { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string Heading { get; set; }
        public string Text { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> WarningColorCode { get; set; }
        public string WarningMessage { get; set; }
        public string ip_address { get; set; }
    }
}
