//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website_Structure
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> underwhichnode { get; set; }
        public string level { get; set; }
        public Nullable<int> linkedid { get; set; }
        public Nullable<int> sequence { get; set; }
        public Nullable<int> underwhichnode1 { get; set; }
        public Nullable<int> underwhichnode2 { get; set; }
        public Nullable<int> underwhichnode3 { get; set; }
        public string dept { get; set; }
        public Nullable<bool> SubDepartment { get; set; }
        public string email { get; set; }
        public string notesForSwitchboard { get; set; }
        public string NewNameForSubDepartment { get; set; }
        public string SubDepartmentNameForSwitchboard { get; set; }
        public string NewNameForDepartment { get; set; }
    }
}
