//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website_Department_Structure
    {
        public string Name { get; set; }
        public string Title1 { get; set; }
        public string Description1 { get; set; }
        public string Keywords1 { get; set; }
        public string container1 { get; set; }
        public string Heading11 { get; set; }
        public string Heading21 { get; set; }
        public string Overview1 { get; set; }
        public string Services1 { get; set; }
        public string Our_Team1 { get; set; }
        public string News1 { get; set; }
        public string left_under_deptmenu1 { get; set; }
        public string leftimage_under_deptmenu1 { get; set; }
        public string folder1 { get; set; }
        public string folderteam1 { get; set; }
        public string contactstr1 { get; set; }
        public int ID { get; set; }
        public string departmenttype { get; set; }
        public string NameForNavigation { get; set; }
        public string lawlogoimg { get; set; }
        public string cssclass { get; set; }
        public Nullable<bool> BusinessOrPersonal { get; set; }
        public string Video { get; set; }
        public Nullable<int> Sequence { get; set; }
        public string NameforHomePage { get; set; }
        public Nullable<int> Private { get; set; }
        public Nullable<int> LegalAid { get; set; }
        public Nullable<int> Corporate { get; set; }
    }
}
