//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website_Pages
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Department { get; set; }
        public string Sub_Department { get; set; }
        public string Keywords { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Text { get; set; }
        public string Sub_Sub_Department { get; set; }
        public string Filename { get; set; }
        public string RewriteURL { get; set; }
        public string Company { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<System.DateTime> date_update { get; set; }
        public string anchortextnavigation { get; set; }
        public Nullable<System.DateTime> DateUpdated { get; set; }
        public string AltTagIng1 { get; set; }
        public string AltTagIng2 { get; set; }
        public string AltTagIng3 { get; set; }
        public string AltTagIng4 { get; set; }
        public string AltTagIng5 { get; set; }
        public string AltTagIng6 { get; set; }
        public string AltTagIng7 { get; set; }
        public string CustomSubDepartment { get; set; }
        public string SubDepartmentSwitchboard { get; set; }
        public string CustomDepartment { get; set; }
    }
}
