//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebsitePagesSubDepartment
    {
        public int ID { get; set; }
        public string WebPageName { get; set; }
        public string Dept { get; set; }
        public string SubDept { get; set; }
    }
}
