//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class Website_Structure
    {
        public Website_Structure()
        {
            this.Website_Structure1 = new HashSet<Website_Structure>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> underwhichnode { get; set; }
        public Nullable<int> underwhichnode1 { get; set; }
        public Nullable<int> underwhichnode2 { get; set; }
        public Nullable<int> underwhichnode3 { get; set; }
        public string level { get; set; }
        public Nullable<int> linkedid { get; set; }
        public Nullable<decimal> sequence { get; set; }
        public string dept { get; set; }
        public Nullable<bool> SubDepartment { get; set; }
        public string email { get; set; }
        public string notesForSwitchboard { get; set; }
        public string NewNameForSubDepartment { get; set; }
        public string SubDepartmentNameForSwitchboard { get; set; }
        public string NewNameForDepartment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> Enabled { get; set; }
        public Nullable<int> WarningColorCode { get; set; }
        public string WarningMessage { get; set; }
        public string ip_address { get; set; }
    
        public virtual Website_Pages Website_Pages { get; set; }
        public virtual ICollection<Website_Structure> Website_Structure1 { get; set; }
        public virtual Website_Structure Website_Structure2 { get; set; }
    }
}
