//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dlwebclasses
{
    using System;
    using System.Collections.Generic;
    
    public partial class website_Header_Pictures
    {
        public int id { get; set; }
        public string department { get; set; }
        public string Picture_Heading { get; set; }
        public string Picture_Blurb { get; set; }
        public string imgfilename { get; set; }
        public string mobileimgfilename { get; set; }
        public Nullable<bool> updated { get; set; }
    }
}
