//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLCMS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DLCMS_ITDatabase : DbContext
    {
        public DLCMS_ITDatabase()
            : base("name=DLCMS_ITDatabase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Updates_MainWebsites> Updates_MainWebsites { get; set; }
        public virtual DbSet<Website_Pages> Website_Pages { get; set; }
        public virtual DbSet<Website_Structure> Website_Structure { get; set; }
        public virtual DbSet<Website_Videos> Website_Videos { get; set; }
        public virtual DbSet<website_Office_Direction> website_Office_Direction { get; set; }
        public virtual DbSet<website_awards> website_awards { get; set; }
    }
}
