//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DLCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Updates_MainWebsites
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Brief { get; set; }
        public string Contents { get; set; }
        public Nullable<System.DateTime> Date_Update { get; set; }
        public Nullable<System.DateTime> Date_Added { get; set; }
        public string Department { get; set; }
        public bool Live { get; set; }
        public string Description { get; set; }
        public string Keywords { get; set; }
        public string Blog_Department { get; set; }
        public Nullable<int> Total_Comments { get; set; }
        public Nullable<bool> Image { get; set; }
        public Nullable<long> Duplicate_ID { get; set; }
        public string KeywordsToBeUsed { get; set; }
        public string Page_Title { get; set; }
        public string DLorNonDL { get; set; }
        public string Staff1 { get; set; }
        public string Staff2 { get; set; }
        public string Staff3 { get; set; }
        public string category { get; set; }
        public bool video { get; set; }
        public string filename { get; set; }
        public string Staff4 { get; set; }
        public string Staff5 { get; set; }
        public string Staff6 { get; set; }
        public string Staff7 { get; set; }
        public string Staff8 { get; set; }
        public string Staff9 { get; set; }
        public string Staff10 { get; set; }
    }
}
